version: "3"
services:
  editor:
    image: subscription:0.0.1
    container_name: subscription
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - SERVER_ADDRESS=0.0.0.0
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database/database


  database:
    image: postgres:14-alpine3.18
    container_name: database
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "15432:5432"
    volumes:
      - subscription-db:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d database" ]
      interval: 5s
      retries: 5
      timeout: 10s



volumes:
  subscription-db: